### ISSUE TITLE
Babel Relay Plugin errors when running

### ISSUE THREAD

**Issue by justinwoo** [reindexio/reindex-todomvc#4]
When I try to run `npm init`, I get the following errors:

```
ERROR in ./src/components/TodoApp.js
Module build failed: AssertionError: /Users/jwoo/Code/reindex-todomvc/multi-user/src/components/TodoApp.js: getBabelRelayPlugin(): Expected schema to be an object with a `__schema` property.
    at getSchema (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-relay-plugin/src/getBabelRelayPlugin.js:213:3)
    at NodePath.Plugin.visitor.TaggedTemplateExpression (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-relay-plugin/src/getBabelRelayPlugin.js:103:26)
    at NodePath.call (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/index.js:76:17)
 @ ./src/components/App.js 43:15-35

ERROR in ./src/routes/AppRoute.js
Module build failed: AssertionError: /Users/jwoo/Code/reindex-todomvc/multi-user/src/routes/AppRoute.js: getBabelRelayPlugin(): Expected schema to be an object with a `__schema` property.
    at getSchema (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-relay-plugin/src/getBabelRelayPlugin.js:213:3)
    at NodePath.Plugin.visitor.TaggedTemplateExpression (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-relay-plugin/src/getBabelRelayPlugin.js:103:26)
    at NodePath.call (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/jwoo/Code/reindex-todomvc/multi-user/node_modules/babel-core/lib/traversal/index.js:76:17)
 @ ./src/components/App.js 47:22-51
```

Still get this issue if I lock down the package versions. Ideas?... I'm pushing and fetching the schema in this package and all.

**Comment by freiksenet** [comment]
What are the contents of your `data/schema.json`?

**Comment by justinwoo** [comment]
```json
[
  {
    "name": "Todo",
    "kind": "OBJECT",
    "interfaces": [
      "Node"
    ],
    "fields": [
      {
        "name": "complete",
        "type": "Boolean"
      },
      {
        "name": "id",
        "type": "ID",
        "nonNull": true
      },
      {
        "name": "text",
        "type": "String"
      },
      {
        "name": "user",
        "type": "User",
        "reverseName": "todos"
      }
    ]
  },
  {
    "name": "User",
    "kind": "OBJECT",
    "interfaces": [
      "Node"
    ],
    "fields": [
      {
        "name": "id",
        "type": "ID",
        "nonNull": true
      },
      {
        "name": "todos",
        "type": "Connection",
        "ofType": "Todo",
        "reverseName": "user"
      }
    ]
  }
]
```

as a result of `reindex schema-push ReindexSchema.json; reindex schema-fetch data/schema.json --force;`

**Comment by freiksenet** [comment]
I mean the generated schema for relay, that you get when you do `reindex schema-relay`. It should be in `data/schema.json`.

**Comment by justinwoo** [comment]
Oh... I misread the instructions. Didn't realize that it said `relay`, not `fetch`. Sorry... :pray:

**Comment by freiksenet** [comment]
So it works fine now?

Cool, glad I could help.
